drop table bank if exists;
create table bank (
                      id bigint generated by default as identity,
                      account_number integer not null,
                      owner varchar(255),
                      balance double not null,
                      primary key (id)
);

insert into bank values (1, 1, 'Anderson', 100.0),
                        (2, 2, 'Giuseppe', 100.0),
                        (3, 3, 'Saraiva', 100.0),
                        (4, 4, 'Patriarca', 100.0);